### ISSUE TITLE
kustomize failed to build the manifest 

### ISSUE THREAD

**Issue by morvencao** [gyliu513/cluster-api-provider-ibmcloud#3]
After I fix the depend inssue: https://github.com/gyliu513/cluster-api-provider-ibmcloud/issues/1 with patch: https://github.com/gyliu513/cluster-api-provider-ibmcloud/pull/2, I found another issue about the `kustomize build`:

```
kustomize build config/default/ > provider-components.yaml
Error: rawResources failed to read Resources: Load from path ../rbac/rbac_role.yaml failed: security; file '../rbac/rbac_role.yaml' is not in or below '/root/gocode/src/sigs.k8s.io/cluster-api-provider-ibmcloud/config/default'

Makefile:33: recipe for target 'manifests' failed
make: *** [manifests] Error 1
```

/cc @gyliu513

**Comment by gyliu513** [comment]
@xunpan is it caused by kustomize version?

**Comment by xunpan** [comment]
Yes. It is kustomize version case. I remember there is a bug in cluster api to compatible with new kustomize.

My old test environment use 1.0.11. It should work.
@morvencao  you can have a try

**Comment by morvencao** [comment]
@xunpan Thanks, let me give it a try.

**Comment by jichenjc** [comment]
@morvencao FYI
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/301

**Comment by morvencao** [comment]
Confirmed this is `kustomize` version issue.

Downgrading the `kustomize` version from `2.0.3` to `1.0.11` fixed this issue.
