### ISSUE TITLE
`go vet` failed

### ISSUE THREAD

**Issue by gyliu513** [gyliu513/cluster-api-provider-ibmcloud#8]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
root@gyliu-dev1:~/go/src/sigs.k8s.io/cluster-api-provider-ibmcloud# go vet ./pkg/... ./cmd/...
# sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/apis/ibmcloud/v1alpha1
pkg/apis/ibmcloud/v1alpha1/zz_generated.deepcopy.go:278:15: in.Datacenter.DeepCopyInto undefined (type datatypes.Location has no field or method DeepCopyInto)
# sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/apis/ibmcloud/v1alpha1 [sigs.k8s.io/cluster-api-provider-ibmcloud/pkg/apis/ibmcloud/v1alpha1.test]
pkg/apis/ibmcloud/v1alpha1/zz_generated.deepcopy.go:278:15: in.Datacenter.DeepCopyInto undefined (type datatypes.Location has no field or method DeepCopyInto)
```

Related to https://github.com/gyliu513/cluster-api-provider-ibmcloud/pull/7#issuecomment-482605729

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment]
https://github.com/gyliu513/cluster-api-provider-ibmcloud/pull/9

**Comment by jichenjc** [comment]
should close this one due to #9
